# Generated by Django 4.2.5 on 2024-01-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pmp_user',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='Enter Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('phone', models.BigIntegerField(verbose_name='Enter Phone Number')),
            ],
            options={
                'db_table': 'pmp_users',
            },
        ),
    ]
