# Generated by Django 4.2.5 on 2024-01-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('assets', '__first__'),
        ('asset_pricing', '0002_alter_asset_pricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset_pricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='ticker',
            field=models.ForeignKey(default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='asset_price_relation', to='assets.asset'),
        ),
        migrations.AlterUniqueTogether(
            name='asset_pricing',
            unique_together={('ticker', 'timestamp1')},
        ),
        migrations.RemoveField(
            model_name='asset_pricing',
            name='ticket',
        ),
    ]
