#services:
#  postgres:
#    environment:
#      POSTGRES_DB: pmp
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 011000101
#    volumes:
#      - pmp_dump.sql:/docker-entrypoint-initdb.d/pmp_dump.sql
#      -
#version: '3.8'
#services:
#  postgres:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: pmp
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 011000101
#    ports:
#      - '5440:5432'
#    volumes:
#      #db:/var/lib/postgresql/data
#      - ./pmp_dump.sql:/docker-entrypoint-initdb.d/create_tables.sql

#volumes:
#  db:
#    driver: local
services:
  timescaledb1:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_DB: pmp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 011000101
    ports:
      - '5440:5432'
    expose:
      - 5440

  # pmp:
  #   image: pmp
  #   restart: always
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - timescaledb1
  #   environment:
  #     - TIMESCALEDB_HOST=timescaledb1
  #     - TIMESCALEDB_PASSWORD=2359361

    
    # volumes:
      #db:/var/lib/postgresql/data
      # - ./pmp_dump.sql:/docker-entrypoint-initdb.d/create_tables.sql