# Generated by Django 4.2.5 on 2023-09-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Enter Ticker')),
                ('category', models.CharField(max_length=20, verbose_name='Enter Category Name')),
                ('name', models.CharField(max_length=20, verbose_name='Enter Name')),
                ('description', models.CharField(max_length=60, verbose_name='Enter Description')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
