# Generated by Django 4.2.5 on 2024-02-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enter Ticker')),
                ('category', models.CharField(max_length=20, verbose_name='Enter Category Name')),
                ('name', models.CharField(max_length=20, verbose_name='Enter Name')),
                ('description', models.CharField(max_length=60, verbose_name='Enter Description')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
