# Generated by Django 4.2.5 on 2023-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='asset_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10, verbose_name='Enter Ticker')),
                ('market_traded', models.CharField(max_length=20, verbose_name='Market Traded')),
                ('market_value', models.IntegerField(verbose_name='Market Value')),
                ('timestamp1', models.DateTimeField()),
                ('currency', models.CharField(max_length=10, verbose_name='Enter Currency')),
            ],
            options={
                'db_table': 'asset_pricing1',
                'unique_together': {('ticket', 'market_traded', 'timestamp1')},
            },
        ),
    ]
