# Generated by Django 4.2.5 on 2024-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_pricing', '0002_alter_asset_pricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_pricing',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
