# Generated by Django 4.2.5 on 2024-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_pricing', '0003_asset_pricing_close_asset_pricing_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_pricing',
            name='ft_week_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='ft_week_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='month_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='month_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='overall_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='overall_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
