# Generated by Django 4.2.5 on 2024-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_pricing', '0004_asset_pricing_ft_week_high_asset_pricing_ft_week_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_pricing',
            name='day_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset_pricing',
            name='day_change_percentage',
            field=models.FloatField(default=0),
        ),
    ]
