# Generated by Django 4.2.5 on 2024-01-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pmp_user', '0001_initial'),
        
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pmp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to='pmp_user.pmp_user')),
                ('watchlist_assets', models.ManyToManyField(blank=True, related_name='watchlist_assets', to='assets.asset')),
            ],
            options={
                'db_table': 'watchlists',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_asset', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to='pmp_user.pmp_user')),
            ],
            options={
                'db_table': 'portfolio_items',
            },
        ),
    ]
