# Generated by Django 4.2.5 on 2024-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_user_portfolio_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='buy_price',
            new_name='avg_buy_price',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='sell_price',
            new_name='avg_sell_price',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
