# Generated by Django 4.2.5 on 2024-03-07 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmp_user', '0001_initial'),
        ('portfolio', '0004_rename_buy_price_portfolio_avg_buy_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDailyOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 16, 28, 28, 144198))),
                ('total_investment', models.FloatField()),
                ('current_value', models.FloatField()),
                ('change_current_value', models.FloatField(default=0)),
                ('change_total_investment', models.FloatField(default=0)),
                ('day_pl', models.FloatField()),
                ('day_pl_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_daily_user', to='pmp_user.pmp_user')),
            ],
            options={
                'db_table': 'portfolios_daily',
                'indexes': [models.Index(models.F('user'), models.F('timestamp'), name='user_portfoliodaily_idx')],
            },
        ),
    ]
