# Generated by Django 4.2.5 on 2024-03-09 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfoliodailyoverview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodailyoverview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 23, 33, 11, 836600)),
        ),
    ]
