# Generated by Django 4.2.5 on 2024-03-10 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfoliodailyoverview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodailyoverview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 21, 18, 12, 728093)),
        ),
    ]
